apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy #base64 encoded name (run echo -n mongouser | base64)
  mongo-password: bW9uZ29wYXNzd29yZA== #base64 encoded name (run echo -n mongopassword | base64)